loc.cloud=C:/test
loc.local=C:/Program Files (x86)/Steam/steamapps/common/ARK Survival Ascended
loc.backup=C:/test_backup
sync.player=false
sync.obelisk=false
sync.maps=false
period.player=2
period.obelisk=1
period.maps=5
task.download=false
task.sync=false
backup.hourly=true
backup.daily=true
backup.weekly=true
backup.monthly=true
backup.wipe=true
wipe.hour=10
wipe.day=6
wipe.week=6
wipe.month=12